apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pdcm-web-ui-dev
  namespace: pdcm-web-ui-dev
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: pdcm-web-ui-dev
    spec:
      containers:
        - name: pdcm-web-ui-dev
          image: "pdxfinder/cancer-models:dev"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
