apiVersion: v1
kind: Service
metadata:
  name: pdcm-web-ui-dev-service
  namespace: pdcm-web-ui-dev
  labels:
    name: pdcm-web-ui-dev-service
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32201
  selector:
    app: pdcm-web-ui-dev
  type: NodePort
