apiVersion: v1
kind: Service
metadata:
  name: cancer-models-dev-service
  namespace: cancer-models-dev
  labels:
    name: cancer-models-dev-service
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: cancer-models-dev
  type: NodePort
