export default [
	{
		patient_age: "40 - 49",
		patient_sex: "female",
		external_model_id: "LCF15",
		model_type: "xenograft",
		data_source: "Curie-LC",
		histology: "Lung Adenocarcinoma",
		primary_site: "lung",
		collection_site: "lung",
		tumour_type: "Primary",
		dataset_available: [
			"mutation",
			"cytogenetics",
			"copy number alteration",
			"dosing studies",
			"publication",
		],
	},
	{
		patient_age: "Not specified",
		patient_sex: "male",
		external_model_id: "ES-4",
		model_type: "xenograft",
		data_source: "PIVOT",
		histology: "Ewing Sarcoma",
		primary_site: "8th rib",
		collection_site: "lung/pleura",
		tumour_type: "Recurrent",
		dataset_available: [
			"mutation",
			"copy number alteration",
			"expression",
			"patient treatment",
			"publication",
		],
	},
	{
		patient_age: "60 - 69",
		patient_sex: "female",
		external_model_id: "BB6RC37",
		model_type: "xenograft",
		data_source: "UOM-BC",
		histology: "Invasive Breast Carcinoma of No Special Type",
		primary_site: "breast",
		collection_site: "breast",
		tumour_type: "Recurrent",
		dataset_available: [
			"mutation",
			"cytogenetics",
			"expression",
			"patient treatment",
			"publication",
		],
	},
	{
		patient_age: "Not specified",
		patient_sex: "male",
		external_model_id: "ALL-07",
		model_type: "xenograft",
		data_source: "PIVOT",
		histology: "B Acute Lymphoblastic Leukemia",
		primary_site: "not provided",
		collection_site: "bone marrow",
		tumour_type: "Primary",
		dataset_available: [
			"mutation",
			"copy number alteration",
			"expression",
			"patient treatment",
			"publication",
		],
	},
	{
		patient_age: "Not specified",
		patient_sex: "male",
		external_model_id: "KT-10",
		model_type: "xenograft",
		data_source: "PIVOT",
		histology: "Wilms Tumor",
		primary_site: "left kidney",
		collection_site: "left kidney",
		tumour_type: "Primary",
		dataset_available: [
			"mutation",
			"copy number alteration",
			"expression",
			"patient treatment",
			"publication",
		],
	},
	{
		patient_age: "Not specified",
		patient_sex: "female",
		external_model_id: "OS-31",
		model_type: "xenograft",
		data_source: "PIVOT",
		histology: "Osteosarcoma",
		primary_site: "not provided",
		collection_site: "right distal femur",
		tumour_type: "Primary",
		dataset_available: [
			"mutation",
			"copy number alteration",
			"expression",
			"patient treatment",
			"publication",
		],
	},
	{
		patient_age: "Not specified",
		patient_sex: "male",
		external_model_id: "Rh-30",
		model_type: "xenograft",
		data_source: "PIVOT",
		histology: "Fusion-Positive Rhabdomyosarcoma",
		primary_site: "posterior fossa",
		collection_site: "bone marrow",
		tumour_type: "Primary",
		dataset_available: [
			"mutation",
			"copy number alteration",
			"expression",
			"patient treatment",
			"publication",
		],
	},
	{
		patient_age: "60 - 69",
		patient_sex: "female",
		external_model_id: "T283",
		model_type: "xenograft",
		data_source: "NKI",
		histology: "Invasive Breast Carcinoma of No Special Type",
		primary_site: "breast",
		collection_site: "breast",
		tumour_type: "Primary",
		dataset_available: [
			"mutation",
			"cytogenetics",
			"copy number alteration",
			"expression",
			"publication",
		],
	},
	{
		patient_age: "60 - 69",
		patient_sex: "female",
		external_model_id: "BB3RC31",
		model_type: "xenograft",
		data_source: "UOM-BC",
		histology: "Invasive Breast Carcinoma of No Special Type",
		primary_site: "breast",
		collection_site: "pleural effusion",
		tumour_type: "Metastatic",
		dataset_available: [
			"mutation",
			"cytogenetics",
			"expression",
			"patient treatment",
			"publication",
		],
	},
	{
		patient_age: "Not specified",
		patient_sex: "male",
		external_model_id: "G401",
		model_type: "xenograft",
		data_source: "PIVOT",
		histology: "Rhabdoid Tumor",
		primary_site: "kidney",
		collection_site: "kidney",
		tumour_type: "Primary",
		dataset_available: [
			"mutation",
			"copy number alteration",
			"expression",
			"patient treatment",
			"publication",
		],
	},
];
