const mockData = [
	{
		pdcmId: "SIDM00861",
		sourceId: "CMP",
		datasource: "",
		providerName: "Cell Model Passports",
		histology: "Ovarian Clear Cell Adenocarcinoma",
		primarySite: "ovary",
		collectionSite: "ovary",
		tumourType: "Not Provided",
		dataAvailable: ["mutation", "copy number alteration", "expression"],
		modelType: "cell line",
		patientAge: "40 - 49",
		patientSex: "female",
		score: 0,
		modelAvailable: true
	},
	{
		pdcmId: "SIDM01525",
		sourceId: "CMP",
		datasource: "",
		providerName: "Cell Model Passports",
		histology: "Acute Myeloid Leukemia",
		primarySite: "haematopoietic and lymphoid",
		collectionSite: "not collected",
		tumourType: "Not Collected",
		dataAvailable: ["mutation", "copy number alteration", "expression"],
		modelType: "cell line",
		patientAge: "10 - 19",
		patientSex: "female",
		score: 0,
		modelAvailable: true
	},
	{
		pdcmId: "SIDM01483",
		sourceId: "CMP",
		datasource: "",
		providerName: "Cell Model Passports",
		histology: "Cutaneous Melanoma",
		primarySite: "skin",
		collectionSite: "pelvis",
		tumourType: "Metastatic",
		dataAvailable: ["mutation", "copy number alteration", "expression"],
		modelType: "cell line",
		patientAge: "60 - 69",
		patientSex: "female",
		score: 0,
		modelAvailable: true
	},
	{
		pdcmId: "SIDM00340",
		sourceId: "CMP",
		datasource: "",
		providerName: "Cell Model Passports",
		histology: "Plasma Cell Myeloma",
		primarySite: "haematopoietic and lymphoid",
		collectionSite: "peripheral blood",
		tumourType: "Not Provided",
		dataAvailable: ["mutation", "copy number alteration", "expression"],
		modelType: "cell line",
		patientAge: "50 - 59",
		patientSex: "female",
		score: 0,
		modelAvailable: true
	},
	{
		pdcmId: "SIDM00670",
		sourceId: "CMP",
		datasource: "",
		providerName: "Cell Model Passports",
		histology: "Pancreatic Adenocarcinoma",
		primarySite: "pancreas",
		collectionSite: "pancreas",
		tumourType: "Not Provided",
		dataAvailable: ["mutation", "copy number alteration", "expression"],
		modelType: "cell line",
		patientAge: "60 - 69",
		patientSex: "female",
		score: 0,
		modelAvailable: true
	},
	{
		pdcmId: "SIDM01027",
		sourceId: "CMP",
		datasource: "",
		providerName: "Cell Model Passports",
		histology: "Esophageal Squamous Cell Carcinoma",
		primarySite: "esophagus",
		collectionSite: "middle intrathoracic oesophagus",
		tumourType: "Not Provided",
		dataAvailable: ["mutation", "copy number alteration", "expression"],
		modelType: "cell line",
		patientAge: "50 - 59",
		patientSex: "male",
		score: 0,
		modelAvailable: true
	},
	{
		pdcmId: "SIDM01164",
		sourceId: "CMP",
		datasource: "",
		providerName: "Cell Model Passports",
		histology: "Anaplastic Astrocytoma",
		primarySite: "central nervous system",
		collectionSite: "not collected",
		tumourType: "Not Provided",
		dataAvailable: ["mutation", "copy number alteration", "expression"],
		modelType: "cell line",
		patientAge: "60 - 69",
		patientSex: "male",
		score: 0,
		modelAvailable: true
	},
	{
		pdcmId: "SIDM00428",
		sourceId: "CMP",
		datasource: "",
		providerName: "Cell Model Passports",
		histology: "Acute Promyelocytic Leukemia with PML-RARA",
		primarySite: "haematopoietic and lymphoid",
		collectionSite: "bone marrow",
		tumourType: "Not Provided",
		dataAvailable: ["mutation", "copy number alteration", "expression"],
		modelType: "cell line",
		patientAge: "20 - 29",
		patientSex: "female",
		score: 0,
		modelAvailable: true
	},
	{
		pdcmId: "SIDM00723",
		sourceId: "CMP",
		datasource: "",
		providerName: "Cell Model Passports",
		histology: "Lung Non-Small Cell Carcinoma",
		primarySite: "lung",
		collectionSite: "not collected",
		tumourType: "Not Provided",
		dataAvailable: ["mutation", "copy number alteration", "expression"],
		modelType: "cell line",
		patientAge: "Not Provided",
		patientSex: "male",
		score: 0,
		modelAvailable: true
	},
	{
		pdcmId: "SIDM00884",
		sourceId: "CMP",
		datasource: "",
		providerName: "Cell Model Passports",
		histology: "Breast Ductal Carcinoma",
		primarySite: "breast",
		collectionSite: "mammary gland/duct",
		tumourType: "Not Provided",
		dataAvailable: ["mutation", "copy number alteration", "expression"],
		modelType: "cell line",
		patientAge: "40 - 49",
		patientSex: "female",
		score: 0,
		modelAvailable: true
	}
];

export default mockData;
