export const mockData = [
	{
		key: "model",
		name: "Model",
		facets: [
			{
				facetId: "model_type",
				name: "Type",
				type: "check",
				options: ["cell line", "organoid", "PDX", "other"],
				placeholder: null,
				loading: true,
			},
			{
				facetId: "external_model_id",
				name: "Model ID",
				type: "autocomplete",
				options: [],
				placeholder: "TM00015",
				loading: true,
			},
			{
				facetId: "data_source",
				name: "Datasource",
				type: "check",
				options: [
					"BROD",
					"CCIA",
					"CHOP",
					"CMP",
					"CRL",
					"CSHL",
					"Curie-BC",
					"Curie-LC",
					"Curie-OC",
					"DFCI-CPDM",
					"GCCRI",
					"HCI-BCM",
					"IRCC-CRC",
					"IRCC-GC",
					"JAX",
					"LIH",
					"LurieChildrens",
					"MDAnderson",
					"MDAnderson-CCH",
					"NKI",
					"PDMR",
					"PMLB",
					"SANG",
					"SJCRH",
					"TRACE",
					"UMCG",
					"UOC-BC",
					"UOM-BC",
					"VHIO-BC",
					"VHIO-CRC",
					"VHIO-PC",
					"Wistar-MDAnderson-Penn",
					"WUSTL",
				],
				placeholder: null,
				loading: true,
			},
			{
				facetId: "dataset_available",
				name: "Dataset available",
				type: "check",
				options: [
					"copy number alteration",
					"cytogenetics",
					"dosing studies",
					"expression",
					"mutation",
					"patient treatment",
					"publication",
				],
				placeholder: null,
				loading: true,
			},
			{
				facetId: "project_name",
				name: "Project",
				type: "check",
				options: ["EurOPDX", "HCMI", "PDXNet", "PIVOT"],
				placeholder: null,
				loading: true,
			},
		],
	},
	{
		key: "molecular_data",
		name: "Molecular Data",
		facets: [
			{
				facetId: "breast_cancer_biomarkers",
				name: "Breast cancer biomarkers",
				type: "check",
				options: [
					"ER/ESR1 negative",
					"ER/ESR1 positive",
					"HER2/ERBB2 negative",
					"HER2/ERBB2 positive",
					"PR/PGR negative",
					"PR/PGR positive",
				],
				placeholder: null,
				loading: true,
			},
			{
				facetId: "makers_with_cytogenetics_data",
				name: "Cytogenetics",
				type: "multivalued",
				options: [],
				placeholder: "ESR1",
				loading: true,
			},
			{
				facetId: "makers_with_expression_data",
				name: "Gene Expression",
				type: "multivalued",
				options: [],
				placeholder: "BEST1",
				loading: true,
			},
			{
				facetId: "makers_with_cna_data",
				name: "Copy Number Alteration",
				type: "multivalued",
				options: [],
				placeholder: "RTP3",
				loading: true,
			},
			{
				facetId: "makers_with_mutation_data",
				name: "Gene mutation",
				type: "multivalued",
				options: [],
				placeholder: "RTP3",
				loading: true,
			},
		],
	},
	{
		key: "patient_tumour",
		name: "Patient / Tumor",
		facets: [
			{
				facetId: "collection_site",
				name: "Collection Site",
				type: "check",
				options: [
					"4th ventricle",
					"abdomen",
					"abdomen ascitis",
					"abdomin",
					"abdomina cavity",
					"abdominal",
					"abdominal mass",
					"abdominal wall",
					"abdominopelvic",
					"adrenal",
					"adrenal cortex",
					"adrenal gland",
					"adrenal mass",
					"adrenal resection",
					"adrenal tissue",
					"alveolus",
					"ampulla",
					"ampulla of vater",
					"anal",
					"anus",
					"aortocaval",
					"arm",
					"ascending colon",
					"asciets",
					"ascites",
					"ascites fluid",
					"axilla",
					"axillary lymph node",
					"back",
					"back mass",
					"back soft tissue",
					"base of tongue",
					"bilateral",
					"bile duct",
					"biliary tract",
					"bladder",
					"bladder dome",
					"blood",
					"bone",
					"bone (left proximal humerus)",
					"bone (right humerus)",
					"bone marrow",
					"bowel",
					"brachial muscle",
					"brain",
					"brain (right cerebellum, right parietal)",
					"brain stem",
					"breast",
					"bronchus",
					"buccal mucosa",
					"buttock",
					"caecum",
					"calf",
					"cecum",
					"cerebellar tentorium",
					"cerebellum",
					"cerebral hemisphere",
					"cerebrospinal fluid",
					"cerebrum",
					"cervical endometrium",
					"cervical lymph node",
					"cervical node",
					"cervical oesophagus",
					"cervix",
					"chest",
					"chest mass",
					"chest wall",
					"chest wall/subcutaneous mass ribs 3-6",
					"clivus",
					"cns",
					"colon",
					"colon nos",
					"colon, sigmoid",
					"common bile duct",
					"common duct node",
					"connective tissue",
					"descending colon",
					"diaphragm",
					"distal esophagus (lower thoracic esophagus)",
					"distal esophagus and proximal stomach",
					"distal femur",
					"distal transverse colon",
					"duodenum",
					"endometrium",
					"erythroleukemia blasts",
					"eso-intrathorasic lymph node",
					"esophagastric junction",
					"esophageal",
					"esophageal lymph node",
					"esophagus",
					"esophagus - distal third",
					"esophagus / lung",
					"esophagus supraclavicular lymph node",
					"extrahepatic bile duct",
					"eye",
					"femalelank mass",
					"femur",
					"floor of mouth",
					"frontal brain lobe",
					"frontal cortex",
					"gall bladder",
					"gastric",
					"gastric fundus",
					"gastric peritoneal noule",
					"gastro-oesophageal junction (cardia)",
					"gastroesophageal junction",
					"gastroesophagel junction",
					"glottis",
					"groin lymph node",
					"hard palate",
					"head",
					"hepatic duct bifurcation",
					"hepatic flexure of colon",
					"hollow bone",
					"humerus",
					"hypopharynx",
					"ileocecal valve",
					"ileum",
					"iliac node (groin)",
					"ilium",
					"inferior leg",
					"infratemporal fossa",
					"inguinal lymph node",
					"inguinal mass",
					"innominate bone",
					"intracranial",
					"intrahepatic duct",
					"intraperitoneal cavity",
					"jaw",
					"jejunum/ilium",
					"kidney",
					"larynx",
					"larynx (glottic)",
					"larynx (subglottic)",
					"left breast",
					"left colon",
					"left distal femur",
					"left femur",
					"left kidney",
					"left knee",
					"left leg",
					"left lower lobe lung",
					"left lower lung lobe",
					"left lung",
					"left occipital mass",
					"left parieto-occipital lobe",
					"left posterior shoulder",
					"left proximal tibia",
					"left supraclavicular lymph node",
					"left supraclavicular region",
					"left temple",
					"left temporal lobe",
					"left thigh",
					"left upper and lower lobe lung",
					"left upper lobe lung",
					"left upper lobe lung invasive into bronchus and lower lobe",
					"left ureter",
					"left vulva",
					"leg",
					"leukapheresis",
					"liver",
					"liver & lung",
					"liver metastasis",
					"liver, left lobe",
					"local lymph node",
					"lower alveolus and gingiva",
					"lower back",
					"lower extremity",
					"lower gingiva",
					"lower intrathoracic oesophagus",
					"lower left lobe lung",
					"lower lobe, lung",
					"lower right lung lobe",
					"lung",
					"lung lymph node",
					"lung mass",
					"lung metastasis",
					"lung/pleura",
					"lymph node",
					"lymph node(s)",
					"lymphatic system",
					"mammary gland",
					"mammary gland/duct",
					"maxilla",
					"mediastinal lymph node",
					"mediastinum",
					"mesenteric lymph node",
					"mesenterium",
					"middle intrathoracic oesophagus",
					"middle lobe, lung",
					"mouth",
					"mouth floor",
					"muscle",
					"neck",
					"neck mass",
					"neck of the urinary bladder",
					"net / axillary lymph node",
					"neural",
					"not collected",
					"not provided",
					"not provided/unknown",
					"not reported",
					"ns",
					"occipital lobe",
					"oesophagus",
					"omentum",
					"oral aveolus",
					"oral cavity",
					"oral floor",
					"oral, gingiva",
					"orbit",
					"oropharynx",
					"os frontalis",
					"ovary",
					"ovary l",
					"pancreas",
					"pancreass",
					"pancreatic body",
					"pancreatic duct",
					"pancreatic head",
					"pancreatic net & liver",
					"pancreatic tail",
					"paracaval lymph node",
					"paracentesis",
					"paragastric lymph node",
					"parapharyngeal",
					"pararenal lymph node",
					"paraspinal mass",
					"paraspinal mass resection",
					"paratesticular",
					"parathyroid / neck",
					"paratracheal lymph node",
					"parietal lobe",
					"pelvic",
					"pelvic mass",
					"pelvis",
					"peri-rectal mass",
					"pericardial effusion",
					"pericardial fluid",
					"pericardium",
					"perineum",
					"peripheral blood",
					"peripheral fluid",
					"peritoneal",
					"peritoneal & ascites",
					"peritoneal ascites",
					"peritoneal ascitic fluid",
					"peritoneal cavity",
					"peritoneal effusion",
					"peritoneal fluid",
					"peritoneal mass",
					"peritoneum",
					"peritracheal",
					"pharynx",
					"pineal",
					"placenta",
					"pleura",
					"pleural cavity",
					"pleural effusion",
					"pleural effusion fluid",
					"pleural fluid",
					"plueral effusion",
					"pontine meninges",
					"post mortem blood",
					"post mortem liver",
					"post-cricoid",
					"posterior fossa",
					"posterior mediastinum",
					"primary colon",
					"primary colon & liver",
					"primary colon l",
					"primary colon r",
					"primary colon recto-sigmoid",
					"primary colon sigmoid",
					"primary tumour",
					"prostate",
					"prostate gland",
					"pyloric lymph nodes",
					"rectal / abdomen",
					"rectosigmoid junction",
					"rectum",
					"rectum and distal sigmoid",
					"renal",
					"renal pelvis",
					"retro-peritoneal lymph node",
					"retromolar trigone",
					"retroperitoneal embroyonal tumour",
					"retroperitoneal lymph node",
					"retroperitoneal mass",
					"retroperitoneum",
					"right axillary lymph node",
					"right breast",
					"right breast metastasis",
					"right buttock",
					"right cheek",
					"right colon",
					"right distal femur",
					"right femur/rib/vertebra",
					"right frontal parieto-occipital cortex",
					"right humerus",
					"right inguinal mass",
					"right kidney",
					"right lower lobe",
					"right lower lobe lung",
					"right neck mass",
					"right parietal lobe",
					"right popliteal",
					"right proximal ulna",
					"right sylvian fissure",
					"right temporal lobe",
					"right upper lobe lung",
					"sacral bone",
					"sacral vertebrae",
					"salivary gland",
					"scalp",
					"scalp and right parotid",
					"scapula",
					"shoulder",
					"shoulder tumour",
					"sigmoid",
					"sigmoid colon",
					"sigmoid colon and distal anastomotic margin",
					"sigmoid/rectum",
					"skeletal muscle",
					"skin",
					"skin (lower leg)",
					"skin back",
					"skin of breast",
					"skin, left thigh",
					"skin, left upper back",
					"skin, right leg",
					"skin, right posterior arm",
					"small intestine",
					"soft tissue",
					"soft tissue, left lateral mallelos",
					"spinal fluid",
					"spine",
					"spleen",
					"splenic flexure of colon",
					"sternal mass",
					"stomach",
					"stomach (nos)",
					"subcutaneous plasmacytoma",
					"subcutaneous tissue",
					"submaxillary salivary gland",
					"subserosa of fallopian tube",
					"superior leg",
					"supra-orbital area",
					"supraclavicular",
					"supraclavicular fossa",
					"supraclavicular lymph node",
					"supraglottis",
					"synovium",
					"temporal cortex",
					"temporal lobe",
					"temporo-occipital lobe",
					"testes",
					"testis",
					"thalamus",
					"thigh",
					"thigh muscle",
					"thoracic lymph node",
					"thoracic mass",
					"thorax",
					"thumb",
					"thyroid",
					"thyroid (retrosternal mass)",
					"tibia",
					"tongue",
					"tonsil",
					"transverse",
					"transverse and left colon",
					"transverse colon",
					"umbilicus",
					"under finger nail",
					"upper (cervical) oesophagus",
					"upper limb nos",
					"upper lobe, lung",
					"upper maxilla",
					"upper mid descending colon",
					"urinary bladder",
					"uterine body",
					"uterine cervix",
					"uterine corpus",
					"uterus",
					"uveal melanoma",
					"vagina",
					"ventricular mass",
					"vertebral bone",
					"vulva",
					"other",
				],
				placeholder: null,
				loading: true,
			},
			{
				facetId: "primary_site",
				name: "Primary Site",
				type: "check",
				options: [
					"4th ventricle",
					"8th rib",
					"abdomen",
					"abdominal mass",
					"abdominal wall",
					"abdominopelvic",
					"adrenal gland",
					"adrenal mass",
					"adrenal resection",
					"ampulla of vater",
					"ampulla/duodenum",
					"anal",
					"anal cancer",
					"anus",
					"aortocaval",
					"appendix",
					"arm",
					"back",
					"back mass",
					"back soft tissue",
					"base of tongue",
					"bile duct",
					"biliary tract",
					"bladder",
					"bladder cancer",
					"body of the pancreas",
					"bone",
					"bone marrow",
					"brain",
					"brain stem",
					"breast",
					"breast cancer (her2-enriched)",
					"breast cancer (triple negative)",
					"bronchus and lung",
					"buccal mucosa",
					"caecum",
					"calf",
					"cecum",
					"central nervous system",
					"cerebellum",
					"cerebrum",
					"cervix",
					"cervix cancer, caucasian",
					"chest",
					"chest mass",
					"chest wall",
					"colon",
					"colon cancer (asian)",
					"colon cancer (caucasian, europe)",
					"colorectal",
					"connective tissue",
					"cortex of adrenal gland",
					"digestive/gastrointestinal",
					"distal femur",
					"duodenum",
					"endocrine and neuroendocrine",
					"endometrium",
					"epidermal carcinoma",
					"esophagus",
					"extrahepatic bile duct",
					"eye",
					"femalelank mass",
					"femur",
					"floor of mouth",
					"frontal cortex",
					"gallbladder",
					"gastric cancer (caucasian)",
					"gastroesophageal junction",
					"genitourinary",
					"genitourinary tract",
					"glottis",
					"gynecologic",
					"haematopoietic and lymphoid",
					"hard palate",
					"head",
					"head and neck",
					"head of the pancreas",
					"hematologic/blood",
					"hepatic flexure",
					"hepatic flexure of colon",
					"humerus",
					"ileocecal valve",
					"inferior leg",
					"infratemporal fossa",
					"inguinal mass",
					"intrahepatic bile duct",
					"jaw",
					"kidney",
					"large intestine",
					"laryngeal",
					"larynx",
					"left colon",
					"left distal femur",
					"left femur",
					"left kidney",
					"left occipital mass",
					"left proximal humerus/bone marrow",
					"left proximal tibia",
					"leg",
					"leukapheresis",
					"leukemia",
					"leukemia (aml)",
					"liver",
					"liver cancer (caucasian, cholangiocarcinoma)",
					"liver/biliary ducts",
					"lower alveolus and gingiva",
					"lung",
					"lung metastasis",
					"lung recurrence  (what does this mean)",
					"lung recurrence (same)",
					"lymph node",
					"lymphoma",
					"lymphoma (dlbcl)",
					"mediastinum",
					"melanoma",
					"muscle",
					"musculoskeletal",
					"neck",
					"neck mass",
					"neurologic",
					"not collected",
					"not provided",
					"nsclc (caucasian, adenocarcinoma subtype)",
					"nsclc (caucasian, epidermoid subtype)",
					"oesophagus",
					"omentum",
					"oral cavity",
					"orbit",
					"oropharynx",
					"os frontalis",
					"ovary",
					"pancreas",
					"pancreas head",
					"pancreatic cancer (caucasian)",
					"paracaval lymph node",
					"parapharyngeal",
					"paraspinal mass",
					"paraspinal mass resection",
					"paratesticular",
					"parietal lobe",
					"pelvis",
					"perineum",
					"peripheral blood",
					"peripheral nervous system",
					"peritoneal mass",
					"peritracheal",
					"pharynx",
					"pineal",
					"placenta",
					"pleura",
					"pleural cavity",
					"pontine meninges",
					"post-cricoid",
					"posterior fossa",
					"posterior mediastinum",
					"prostate",
					"prostate cancer",
					"prostate gland",
					"rectosigmoid colon",
					"rectosigmoid junction",
					"rectum",
					"renal cancer (caucasian)",
					"respiratory/thoracic",
					"retromolar trigone",
					"retroperitoneal mass",
					"retroperitoneum",
					"right buttock",
					"right colon",
					"right distal femur",
					"right kidney",
					"right neck mass",
					"right parietal lobe",
					"right proximal tibia",
					"right proximal ulna",
					"right sylvian fissure",
					"salivary gland",
					"shoulder",
					"sigmoid colon",
					"sigmoid flexure",
					"skin",
					"small cell lung cancer",
					"small intestine",
					"soft tissue",
					"spine",
					"spleen",
					"splenic flexure of colon",
					"stomach",
					"superior leg",
					"supra-orbital area",
					"supraglottis",
					"tail of the pancreas",
					"temporal cortex",
					"testes",
					"testis",
					"testis cancer",
					"thalamus",
					"thigh",
					"thumb",
					"thyroid",
					"tibia",
					"tongue",
					"tonsil",
					"transverse colon",
					"unknown",
					"unknown primary",
					"uterus",
					"ventricular mass",
					"vulva",
					"other",
					"other (specify)",
				],
				placeholder: null,
				loading: true,
			},
			{
				facetId: "patient_ethnicity",
				name: "Patient Ethnicity",
				type: "check",
				options: [
					"African",
					"African American",
					"Arabic",
					"Asian",
					"Black",
					"Black Or African American",
					"Black Or African American; Not Hispanic Or Latino",
					"Caucasian",
					"Declined To Answer",
					"East Asian",
					"Eastasian",
					"European",
					"Hispanic",
					"Hispanic Or Latino",
					"Latino",
					"Mixed_or_unknown",
					"Not Collected",
					"Not Hispanic Or Latino",
					"Not Provided",
					"South Asian",
					"Southasianorhispanic",
					"Unknown",
					"White",
					"White; Hispanic Or Latino",
					"White; Not Hispanic Or Latino",
					"Native Hawaiian Or Other Pacific Islander",
					"Other",
				],
				placeholder: null,
				loading: true,
			},
			{
				facetId: "cancer_system",
				name: "Cancer system",
				type: "check",
				options: [
					"Breast Cancer",
					"Connective and Soft Tissue Cancer",
					"Digestive System Cancer",
					"Endocrine Cancer",
					"Eye Cancer",
					"Head and Neck Cancer",
					"Hematopoietic and Lymphoid System Cancer",
					"Nervous System Cancer",
					"Peritoneal and Retroperitoneal Cancer",
					"Reproductive System Cancer",
					"Skin Cancer",
					"Thoracic Cancer",
					"Unclassified",
					"Urinary System Cancer",
				],
				placeholder: null,
				loading: true,
			},
			{
				facetId: "patient_age",
				name: "Patient age",
				type: "check",
				options: [
					"0 - 23 months",
					"2 - 9",
					"10 - 19",
					"20 - 29",
					"30 - 39",
					"40 - 49",
					"50 - 59",
					"60 - 69",
					"70 - 79",
					"90 - 99",
					"Not Provided",
					"80 - 89",
				],
				placeholder: null,
				loading: true,
			},
			{
				facetId: "tumour_type",
				name: "Tumour type",
				type: "check",
				options: [
					"Metastatic",
					"Pre-malignant",
					"Primary",
					"Recurrent",
					"Refractory",
				],
				placeholder: null,
				loading: true,
			},
			{
				facetId: "patient_sex",
				name: "Patient sex",
				type: "check",
				options: ["female", "male", "Not Provided", "other"],
				placeholder: null,
				loading: true,
			},
		],
	},
	{
		key: "treatment_drug_dosing",
		name: "Treatment / Drug dosing",
		facets: [
			{
				facetId: "treatment_list",
				name: "Patient treatment",
				type: "multivalued",
				options: [],
				placeholder: "radiation therapy",
				loading: true,
			},
			{
				facetId: "model_treatment_list",
				name: "Model dosing",
				type: "multivalued",
				options: [],
				placeholder: "cyclophosphamide",
				loading: true,
			},
			{
				facetId: "patient_treatment_status",
				name: "Patient treatment status",
				type: "check",
				options: ["Not Provided", "Not treatment naive", "Treatment naive"],
				placeholder: null,
				loading: true,
			},
		],
	},
];
